Structure To-Do-List
Aduda-Boaz/ToDoList pull request #1
Opened 2022-01-19 21:30 UTC by Aduda-Boaz

This PR is for the to-do-list structure, 
All the requirements have been implemented as per the guidelines.

2022-01-19 22:21 UTC, andersonlebon requested changes
### Hi @Aduda-Boaz 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 
- Webpack is used to set up the project ✔️ 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 22:21 UTC, andersonlebon commented on src/style.css
> +}
One of the requirements states that CSS is created used to style the list using the [captured video](https://www.youtube.com/watch?v=AcUd-_Yjjqg). Please note that the video has more features than the current project, students don't need to style all the features not implemented yet in the video. CSS must be loaded by *Webpack Style/CSS Loader*. here 👇 
![image](https://user-images.githubusercontent.com/65068771/150223070-ed2c160a-02ac-4bb5-add1-9d4b57ad97ae.png)

- [ ] Kindly you need to follow the styling in the video demonstration as the requirement says. here is your design 👇 
![image](https://user-images.githubusercontent.com/65068771/150222609-27354450-8d8d-40b2-8da7-1ce53dbb6cdc.png)

2022-01-20 17:17 UTC, Aduda-Boaz commented
Fix the styling of the application to match the design.

2022-01-20 17:26 UTC, leolpaz approved these changes
Hi @Aduda-Boaz , 

Your project is complete!
Congratulations! 🎉🎉 

Now there is nothing left to do but to merge it! 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-20 17:29 UTC, merged